### ISSUE TITLE
Popup not opening in chrome extension

### ISSUE THREAD

**Issue by fmontserrat** [drahoslavzan/popsaurus#1]
Hello @drahoslavzan!

I tried installing PS on Chrome and the popup is not opening:

![popsauruschrome](https://user-images.githubusercontent.com/936743/83761354-7eaf7080-a676-11ea-8fb3-d4d0262d61be.gif)

No output on console or any action.

Chrome version:
`Version 83.0.4103.97 (Official Build) (64-bit)`

**Comment by drahoslavzan** [comment]
Hi,

Extensions are not working inside Chrome Web Store. I think it has to do something with Google policy about extensions.

**Try another page**, for example something on google.com
